from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol
from uuid import UUID

from supportmind.domain.alerting.entities import AlertRequest, AlertRequestDecision, Incident
from supportmind.domain.catalog.entities import AuditEntry, Product
from supportmind.domain.common.enums import Priority, Sentiment
from supportmind.domain.conversation.entities import ConversationSession, DecisionNode, DecisionTree
from supportmind.domain.identity.entities import Agent
from supportmind.domain.sla.entities import SlaPolicy, TicketSlaClock
from supportmind.domain.ticketing.entities import Ticket


@dataclass
class EnrichmentResult:
    priority: Priority
    category: str
    sentiment: Sentiment
    summary: str
    provider: str
    model: str
    prompt_version: str
    raw: dict[str, Any] | None = None


class AIProviderPort(Protocol):
    async def enrich_ticket(
        self,
        *,
        description: str,
        leaf_code: str,
        path_codes: list[str],
        product_name: str,
        transcript: list[dict[str, Any]],
    ) -> EnrichmentResult: ...


class AgentRepositoryPort(Protocol):
    async def get_by_email(self, email: str) -> Agent | None: ...
    async def get_by_id(self, agent_id: UUID) -> Agent | None: ...
    async def list_agents(self) -> list[Agent]: ...
    async def list_available_l1(self) -> list[Agent]: ...
    async def save(self, agent: Agent) -> Agent: ...
    async def increment_open_count(self, agent_id: UUID) -> None: ...


class ProductRepositoryPort(Protocol):
    async def list_active(self) -> list[Product]: ...
    async def get_by_id(self, product_id: UUID) -> Product | None: ...


class DecisionTreeRepositoryPort(Protocol):
    async def get_active_by_slug(self, slug: str) -> DecisionTree | None: ...
    async def get_tree(self, tree_id: UUID) -> DecisionTree | None: ...
    async def get_node(self, node_id: UUID) -> DecisionNode | None: ...
    async def list_trees(self) -> list[DecisionTree]: ...
    async def save_tree(self, tree: DecisionTree) -> DecisionTree: ...


class ConversationRepositoryPort(Protocol):
    async def save(self, session: ConversationSession) -> ConversationSession: ...
    async def get_by_id(self, session_id: UUID) -> ConversationSession | None: ...
    async def get_by_token(self, token: str) -> ConversationSession | None: ...


class TicketRepositoryPort(Protocol):
    async def save(self, ticket: Ticket) -> Ticket: ...
    async def get_by_id(self, ticket_id: UUID) -> Ticket | None: ...
    async def get_by_number(self, number: str) -> Ticket | None: ...
    async def list_tickets(
        self,
        *,
        status: str | None = None,
        assignee_id: UUID | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Ticket]: ...
    async def list_by_fingerprint_since(
        self, fingerprint: str, since_iso_window_seconds: int
    ) -> list[Ticket]: ...
    async def next_sequence(self) -> int: ...
    async def link_to_incident(self, ticket_ids: list[UUID], incident_id: UUID) -> None: ...


class SlaRepositoryPort(Protocol):
    async def get_policy(self, priority: Priority) -> SlaPolicy | None: ...
    async def list_policies(self) -> list[SlaPolicy]: ...
    async def save_clock(self, clock: TicketSlaClock) -> TicketSlaClock: ...
    async def get_clock(self, ticket_id: UUID) -> TicketSlaClock | None: ...


class AlertRepositoryPort(Protocol):
    async def save_request(self, request: AlertRequest) -> AlertRequest: ...
    async def get_request(self, request_id: UUID) -> AlertRequest | None: ...
    async def list_pending(self) -> list[AlertRequest]: ...
    async def get_pending_by_fingerprint(self, fingerprint: str) -> AlertRequest | None: ...
    async def save_decision(self, decision: AlertRequestDecision) -> AlertRequestDecision: ...


class IncidentRepositoryPort(Protocol):
    async def save(self, incident: Incident) -> Incident: ...
    async def get_by_id(self, incident_id: UUID) -> Incident | None: ...
    async def get_active_by_fingerprint(self, fingerprint: str) -> Incident | None: ...
    async def list_incidents(self, *, status: str | None = None) -> list[Incident]: ...
    async def list_active_public(self) -> list[Incident]: ...
    async def next_sequence(self) -> int: ...


class AuditRepositoryPort(Protocol):
    async def append(self, entry: AuditEntry) -> AuditEntry: ...
    async def list_recent(self, *, limit: int = 100) -> list[AuditEntry]: ...


class CorrelationPort(Protocol):
    async def record_and_count(self, fingerprint: str, ticket_id: UUID, window_seconds: int) -> int: ...
    async def try_acquire_alert_lock(self, fingerprint: str, ttl_seconds: int) -> bool: ...


class ObjectStoragePort(Protocol):
    async def upload(
        self, *, bucket: str, key: str, data: bytes, content_type: str
    ) -> str: ...
    async def generate_presigned_url(self, *, bucket: str, key: str, expires_in: int = 3600) -> str: ...


class UnitOfWorkPort(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
